config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users
  resources :users, only: [:show]
  resources :boats do
  resources :bookings
  end 

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user
  has_many_attached :photos

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_description_and_address,
    against: [ :description, :address, :name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something! Full search -> @@ in activeRecord
    }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boat
end

app/models/user.rb
class User < ApplicationRecord
    has_many :boats
    has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :licence_number, :birth_date])
  
      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :licence_number, :birth_date])
    end
  
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
    before_action :set_user
    before_action :set_boat, only: [:show, :edit, :update ]

    def index
      if params[:query].present?
        @boats =Boat.search_by_description_and_address(params[:query])
      else
        @boats = Boat.all
      end 
        @markers = @boats.geocoded.map do |boat|
          {
            lat: boat.latitude,
            lng: boat.longitude,
          }
          
        
        end
    end

    def show
      @markers= [{
        lat: @boat.geocode[0],
        lng: @boat.geocode[1]
      } ]
    end

    def new
        @boat = Boat.new
    end

    def create
      @boat = Boat.new(boat_params)
      @boat.user = @user
      if @boat.save
        redirect_to boats_path
      else
        render "new"
      end
    end

 
    


    def edit
    end
  
    def update
      @boat.update(boat_params)
      redirect_to boat_path(@boat)
    end
  

    def destroy
      set_boat
      @boat.destroy
      redirect_to boats_path
    end

    private

    def set_boat
      @boat = Boat.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    def boat_params
      params.require(:boat).permit(:name, :category, :description, :price_per_day, :address, photos: [])
    end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
before_action :set_boat, only: [:index, :create, :new]

  def index
    @bookings = Booking.all
  end


  def new
  @booking = Booking.new()
  end

  def create

    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.boat = @boat

      if @booking.save
        redirect_to boat_bookings_path(@boat)
      else
        render "new"
      end
  end

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end
  
  private
  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :id )
  end

  def set_boat
    @boat = Boat.find(params[:boat_id])  
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @disable_nav = true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #before_action :authenticate_user!, only: [:show]
    before_action :authenticate_user!, except: [:show]
  
    def show
      @user = User.find(params[:id])
      #redirect_to root_path, notice: "You don't have permission to see this profile" unless current_user == @user
      @boats = @user.boats
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/_map_box.html.erb
<h2><%= boat.name %></h2>
<p><%= boat.address %></p>

app/views/boats/edit.html.erb
<div class="container form-group">
<%= simple_form_for(@boat) do |f| %>
  <%= f.input :name %>
  <%= f.label :photo %>
   <%= f.input :photos, as: :file, input_html: {multiple: true} %>
  <%= f.input :description %>
  <%= f.label :category %>
  <%= f.select :category, ['Yacht', 'Wind', 'Small'] %>
  <%= f.input :address %>
  <%= f.input :price_per_day, step: 0.01 %>

  
   
  <%= f.submit %>
<% end %>

</div>

app/views/boats/index.html.erb
<div class="top-boats-page">
  <h1>Boats list</h1>
</div>

  <div class="container-perso">
  
  <%= form_tag boats_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Give us a boat name so we can sail for you"
  %>
  <%= submit_tag "Search", class: "btn-boats" %>
  <button class="btn-boats third"> <%= link_to "Add new boat", new_boat_path %> </button> 
  </div>
  
<% end %>










<div class="container-perso">
  <ul class="cards">
    <% @boats.each do |boat| %>
      <% if boat.photos.first.present? %>
        <div class="card-category"> 
          <div class="w3-card-4"> 
            <img src="<%= cl_image_path boat.photos.first.key%>" alt="" class=images-border-radius width=500px length=800px>
          </div>
        
          <div class="w3-container w3-center">
            <p class=p-medium> <%= link_to boat.name, boat_path(boat), {:style=>'color:blue; '} %>
                  <br><%= boat.address %> <br><%= boat.price_per_day %> €</p>
          </div>


        </div>
    <% else %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://source.unsplash.com/1600x900/?boat')" > </div>
      <div class="container">
        <li class="boat-group-item, text-center" style="color: white "> <%= link_to boat.name, boat_path(boat), 
          {:style=>'color:white; '} %> <br><%= boat.address %> <br><%= boat.price_per_day %> €</li>
      </div>
        <% end %>      
    <% end %>
  </ul>

    <div >
    <div type="button" class="btn btn-outline-light btn-rounded" data-mdb-ripple-color="dark">
    
       


    <div class="map-container"><div id="map"
    style="width: 100%; height: 600px;"data-markers="<%= @markers.to_json %>"data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div></div>
</div>

app/views/boats/new.html.erb
<div class="container form">
<%= simple_form_for(@boat) do |f| %>
  <%= f.input :name %>
  <%= f.input :photos, as: :file, input_html: {multiple: true} %>
  <%= f.input :description %>
  <%= f.label :category %>
  <%= f.select :category, ['Large boat', 'Medium boat', 'Small boat'] %>
  <%= f.input :address %>
  <%= f.input :price_per_day, step: 0.01 %>

  
   
  <%= f.submit %>
<% end %>

</div>

app/views/boats/show.html.erb
<div class="top-boats-page">
<br>
  <h1><%= @boat.name %></h1>
</div>

<!-- Page Content -->
<div class="container-perso">
  
    <!-- Portfolio Item Row -->
    <div class="row">
  
      <div class="col-md-8">
        <%= cl_image_tag @boat.photos.first.key, height: 500, width: 750, crop: :fill, class: "w-100 shadow-1-strong rounded mb-8" %>
      </div>
  
      <div class="col-md-4">
        <h3 class="my-3">Boat Description</h3>
        <p><%= @boat.description %></p>
        <br>
        <h3 class="my-3">Boat Details</h3>
                
      <br>
        
        <ul>
          <li><p ><%= @boat.address %></p></li>
          <li><p><%= @boat.category %></p></li>
          <li><p><%= @boat.price_per_day %></p></li>
          <li>  <%= link_to @boat.user.full_name, user_path(@boat.user), {:style=>'color:blue; '} %> <br></li>
        
          <%= link_to "Book now", new_boat_booking_path(@boat), class: "btn btn-primary" %>
        </ul>
      </div>
          

  
    </div>
    <!-- /.row -->
  
    <!-- Related Projects Row -->
    <h3 class="my-4">Boat pictures</h3>
  
    <div class="row">
  
      <div class="col-md-3 col-sm-6 mb-4 rounded-10">
        <a href="#">
              <%= cl_image_tag @boat.photos[1].key, height: 300, width: 500, crop: :fill, class: "w-100 shadow-1-strong rounded mb-8" %>
            </a>
      </div>
  
      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
              <%= cl_image_tag @boat.photos[2].key, height: 300, width: 500, crop: :fill, class: "w-100 shadow-1-strong rounded mb-8" %>
            </a>
      </div>
  
      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
              <%= cl_image_tag @boat.photos[3].key, height: 300, width: 500, crop: :fill, class: "w-100 shadow-1-strong rounded mb-8" %>
            </a>
      </div>
  
      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
              <%= cl_image_tag @boat.photos[4].key, height: 300, width: 400, crop: :fill, class: "w-100 shadow-1-strong rounded mb-8" %>>
            </a>
      </div>
  
    </div>
    <!-- /.row -->
  
  </div>

  <%= link_to "Book now", new_boat_booking_path(@boat) %>

</div>

  <div class="d-flex justify-content-between actions">
    <small class="text-right flex-shrink-0"><%= link_to 'Delete', boat_path, method: :delete, data: { confirm: "Are you sure you want to remove #{@boat.name} from your #{@boat.name} boat"}, class: "btn btn-danger" %></small>
    <small class="text-right flex-shrink-0"><%= link_to 'Edit', edit_boat_path(@boat), class: "btn btn-primary" %></small>
    <small class="text-right flex-shrink-0"><%= link_to 'Back to list', boats_path, class: "btn btn-primary" %></small>
  </div>

  <div class="map-container"><div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
 

app/views/bookings/index.html.erb
<div class="top-boats-page">
  <h1>Bookings list</h1>
</div>



<div class="container">
<%= form_tag boats_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a boat"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
</div>


<% @bookings.each do |booking| %>
    <li>
    <%= link_to booking.user.first_name, boat_booking_path(@boat, booking), {:style=>'color:black; '} %> <br>
    </li>
 <% end %>
</ul>

<div class="container-perso">
<ul>


  <%= link_to "Add new boat", new_boat_path %>
  <br>
  <div class="map-container"><div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div></div>
</div>

app/views/bookings/new.html.erb
#create a form for the booking
<%= simple_form_for([@boat, @booking]) do |f| %>

  <%= f.input :start_date %>
  <%= f.input :end_date %>

<div class="container-perso">
   <h3 class="my-3">Boat Description</h3>
        <p><%= @boat.description %></p>
        <br>
    <!-- Portfolio Item Row -->
<div class="row">
  

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
              <%= cl_image_tag @boat.photos[0].key, height: 300, width: 500, crop: :fill, class: "w-100 shadow-1-strong rounded mb-8" %>
            </a>
      </div>
  
      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
              <%= cl_image_tag @boat.photos[1].key, height: 300, width: 500, crop: :fill, class: "w-100 shadow-1-strong rounded mb-8" %>
            </a>
      </div>
  
      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
              <%= cl_image_tag @boat.photos[2].key, height: 300, width: 500, crop: :fill, class: "w-100 shadow-1-strong rounded mb-8" %>
            </a>
      </div>
  
      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
              <%= cl_image_tag @boat.photos[3].key, height: 300, width: 400, crop: :fill, class: "w-100 shadow-1-strong rounded mb-8" %>>
            </a>
      </div>
        
</div>
         <ul>
          <li><p><strong> Address: </strong> <%= @boat.address %> </p></li>
          <li><p><strong> Category:</strong> <%= @boat.category %></p></li>
          <li><p><strong> Price per day: </strong> <%= @boat.price_per_day %>€</p></li>
          <li><p><strong> Owner :</strong> <%= @boat.user.first_name %> <%= @boat.user.last_name %> </p></li>
        </ul>
<br>
   <%= f.submit %>
<% end %>


                
  

app/views/bookings/show.html.erb
<h1> <%= @booking.boat.name %> </h1>

<h3> Renting request from <%= @booking.user.first_name %> <%= @booking.user.last_name %></h3>

<p>From <%= @booking.start_date.to_s(:long) %> to <%= @booking.end_date.to_s(:long) %></p>

 <% time = @booking.end_date - @booking.start_date %>

<p>price =  <%= time*@booking.boat.price_per_day %> </p>

<% if current_user == @booking.boat.user %>
<p> Accepter ou refuser la réservation ? </p>
    <%= f.input :booking_status %>
<% end %>

       

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentABoat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' unless @disable_nav %>
    <%= render 'shared/flashes' unless @disable_nav %>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="hero-full-screen">


<div class="top-content-section">


  <div class="middle-content-section">
    <h1>Rent-A-Boat</h1>
    <h3>The best solution for your boat rental </h3>
    <section id="hero">
    <% if user_signed_in? %>
      <p> Hi <%= current_user.first_name %></p>  
    <% else %>
        <%= link_to "Log in", new_user_session_path, class: "btn btn-primary" %>
    <% end %>
        <%= link_to "Browse boats", boats_path, class: "btn btn-alert" %>
      </section>
  </div>

<br><br>

<div class="text-center">
 <%= form_tag boats_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a boat by Name, description, or location."
  %>
  <br>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
</div>
 
  <div id="main-content-section" data-magellan-target="main-content-section">
  <!-- your content goes here -->
 

<div class="c mt-10">
  <i class="fab fa-bitcoin mt-10" id="r" width="" height="6"></i>

  


  <i class="fab fa-github"></i>
  

  <i class="fab fa-slack"></i>
  

</div>

</footer

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", boats_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
    <div class="col-md-12" style="color: black ">
        <h1> Welcome to <%= @user.full_name %> boat list</h1>
        <a class="btn btn-primary" href="/boats">Back</a> 
    </div> 

        
        
<div class="row col-12 content">

    

    <% @boats.each do |boat|%>
        <div class="card col-6 card-img-user"> 
            <div class="box" style="aspect-ratio: 1/1; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path boat.photos.first.key,  crop: :fill%>')" >
            <li class="boat-group-item, text-bottom" style="color: white "> <%= link_to boat.name, boat_path(boat), {:style=>'color:white; '} %>  <br></li>
            </div>                   
        </div>
    <% end %>

    
</div>


       
        
    
</div>